version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-default_db}
      POSTGRES_USER: ${POSTGRES_USER:-default_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-default_user} -d ${POSTGRES_DB:-default_db}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
